### ISSUE TITLE
Lab2_Angle_and_RotateCommand

### ISSUE THREAD

**Issue by Danila-Skiba** [Danila-Skiba/OOAIP#28]
7. Угол на плоскости.
Для представления угла наклона к оси OX игрового объекта реализовать класс Angle. Внутри Angle представлен как рациональное число, причем знаменатель у всех углов будет одинаковый (его можно сделать статическим полем). Для угла должна быть реализована операция сложения и должна быть возможность вычисления синуса и косинуса от Angle без предварительного явного приведения к типу Double: Math.Cos(angle).

Критерии приемки:

Реализован тест, который проверяет, что при сложении углов (5, 8) и (7, 8) получается вектор (4,8).
Реализован тест, который проверят, что два угла (15, 8) и (23, 8), равны между собой при сравнении через метод Equals.
Реализован тест, который проверят, что два угла (15, 8) и (23, 8), равны между собой при сравнении через метод ==.
Реализован тест, который проверят, что углы (1,8) и (2, 8) неравны между собой при сравнении через метод Equals.
Реализован тест, который проверят, что углы (1,8) и (2, 8) неравны между собой при сравнении через метод !=.
Реализован тест, который проверяет наличие хэш-кода у угла.
8. Определить команду Rotate для равномерного вращения вокруг собственной оси.
Команда выполняет равномерное поступательное движение объекта без деформации за один дискретный момент времени.

Критерии приемки:

Реализован тест, который проверяет, что если вращающийся объект имеет угол наклона 45 градусов к оси OX и имеет мгновенную угловую скорость 45 градусов, то в следующий дискретный момент времени угол наклона к оси OX будет 90 градусов.
Реализован тест, который проверяет, что если невозможно определить угол наклона объекта к оси OX, то команда Rotate выбрасывает исключение.
Реализован тест, который проверяет, что если у вращающегося объекта невозможно определить мгновенную угловую скорость, то команда Rotate выбрасывает исключение.
Реализован тест, который проверяет, что еcли у движущегося объекта невозможно изменить угол наклона к оси OX, то команда Rotate выбрасывает исключение.

**Comment by zse7** [comment]
done
